---
- hosts: proxy
  become: true
  vars:
    acme_challenge_domain: triactivesoft.com
    acme_challenge_proxmox_domain: proxmox.triactivesoft.com
    domain_admin_email: ibarretorey@gmail.com
    proxmox_url: https://192.168.0.27:8006
  roles:
    - ansibleRoleDocker
    - installProxy