---
- hosts: localhost
  connection: local
  tasks:
    - name: Create local id_rsa ssh keys
      shell: 
        cmd: "./create_id_rsa_ssh.sh"

- hosts: control_plane, workers
  become: true
  gather_facts: true
  tasks:
    - name: Install docker
      include_role:
        name: ansibleRoleDocker
    - name: Prepare k8s nodes
      include_role:
        name: prepare
    - name: Install kube dependencies
      include_role:
        name: installKubeDependencies

- hosts: control_plane
  become: true
  gather_facts: no
  tasks:
    - name: install kubectl
      apt:
        name: kubectl=1.23.5-00
        state: present
        force: yes
    - name: Initialize k8s master node
      include_role:
        name: initMaster
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: 
        cmd: "{{ hostvars['control1'].join_command }}"