---
- name: Create ssh key
  hosts: localhost
  connection: local
  tasks:
    - name: Create local id_rsa ssh keys
      ansible.builtin.shell:
        cmd: "./create_id_rsa_ssh.sh"
      register: output
      changed_when: output.rc == 0

- name: Install docker and kuberenetes dependencies
  hosts: master, workers
  remote_user: vagrant
  environment:
    HOME: "/home/{{ ansible_user }}"
  become: true
  gather_facts: true
  tasks:
    - name: Install docker
      ansible.builtin.include_role:
        name: ansible_role_docker
    - name: Install kube dependencies
      ansible.builtin.include_role:
        name: install_kube_dependencies

- name: Install and configure the master node
  hosts: master
  remote_user: vagrant
  environment:
    HOME: "/home/{{ ansible_user }}"
  become: true
  gather_facts: false
  tasks:
    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl=1.27.2-00
        state: present
        force: true

    - name: Initialize k8s master node
      ansible.builtin.include_role:
        name: init_master

    - name: Get join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_raw
      changed_when: join_command_raw.rc == 0

    - name: Set join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Joining the cluster with workers
  hosts: workers
  remote_user: vagrant
  environment:
    HOME: "/home/{{ ansible_user }}"
  become: true
  tasks:
    - name: Reset and restart containerd service
      become: true
      ansible.builtin.shell: |
        rm -f /etc/containerd/config.toml
        systemctl restart containerd.service
    - name: Join cluster
      ansible.builtin.command: "{{ hostvars[groups['master'][0]].join_command }}"
