---
- name: create the 'ubuntu' user
  user: name=ubuntu append=yes state=present createhome=yes shell=/bin/bash

- name: allow 'ubuntu' to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: set up authorized keys for the ubuntu user
  authorized_key: user=ubuntu key="{{item}}"
  with_file:
    - ~/.ssh/id_rsa.pub

- name: "disable swap"
  command: swapoff -a
- name: "remove swap file"
  lineinfile:
    dest: "{{ prepare.swap_definition }}"
    regexp: "{{ prepare.swap_query }}"
    state: absent
  register: swap_cmd
- name: "reboot"
  reboot:
    post_reboot_delay: "{{ prepare.swap_reboot_wait }}"
  when: swap_cmd.changed == true